package com.zp.sys.dao;

import com.zp.sys.entity.Role;
import com.zp.sys.entity.User;
import com.zp.sys.entity.UserType;

import java.util.List;
import java.util.Map;


public interface UserMapper {
	User login(Map<String,Object> param);
	User wklogin(Map<String,Object> param);
	List<User> appLogin(Map<String,Object> param);
	void updateAppUser(Map<String,Object> param);
	User getUser(Map<String,Object> param);
	List<Map<String,Object>> getUserNameList();
	void updateUser(User user);
	void updateState(User user);
	List<User> listPageOfUser(Map<String,Object> map);
	Long getUserId();
	int addUser(User user);
	Long getuserId();
	void deleteLcCust(User user);
	User getUserById(User user);
	void editUser(User user);
	List<UserType> findTypeList();
	void insertUserRole(Map map);
	void insertUserStore(Map map);
	void deleteRoleUser(User user);
	void deleteStoreUser(User user);
	void updateAppPassWord(Map map);
	List<User> validateUserPassWord(Map map);
	void insertCustContact(Map map);
	void updateCustContact(Map map);
	void deleteCustContact(Map map);
	User getUserInfoByAppKey(String appKey);
	List<User> listPageOfUser2(User user);
	void changeUserPwd(User user);
	String findUserByUserName(String userName);
	void updateLastLogin(User user);
	List<Integer> getUserStoresId(Long userid);
	void updateUserHeadImage(User user);
	String getCustName(Long CustId);
//	String getTypeNameByTypeId(int userType);
	int updateUserTokenForApp(Map map);
	String getExpressByCom(String expressName);
	List<Integer> finLocalStoreIdById(String storeName);
	void delUserDeliveryPoint(User user);
	void addContactUser(Map<String, Object> contactmap);
	List<UserType> findRgTypeList();
	List<User> getKfUserInfo(String appKey);
	List<String> getUserStoresCode(Long userId);
	List<User> exportListOfUser(Map map);
	void updateApplanguage(Map<String, Object> map);
	String getAppLanguageByToken(String token);
	public List<Role> getRoleList();
	Long getUserIdBypasswordandusername(Map<String, Object> param);
	void editContact_phone(User user);
	String getUserNameById(Long userId);
	List<User> getuserPwdErrorNum(Map<String, Object> map);
	void setPwdErrorTimeAndNum(Map<String, Object> map2);
	String getoldPassword(Long id);
	List<User> getuserlistPage(User user);
	//--------------------------以下文库----------------------------------
	void jinUser(User user);
	void recUser(User user);
	User getUserByName(User user);
	User getclnumber(User user);
	User getuploadsum(User user);
	User getnoticesum(User user);
	void wkedituserinfo(User user);
	void wkeditpassword(User user);
	List<User> wkgetmyinfomationlistPage(User user);
	void clearallinfo(User user);
	void chooseclearinfo(User user);
	List<User> wkreadrecord (User user);
	List<User> wkgetcompanynoticelistPage(User user);
	int wkredpoint(User user);
	int wkjudgenoticerecord(User user);
	void wkinsertnoticerecord(User user);
	List<User> getnoticelistPage(User user);
	List<User> getbName(User user);
	void insertnotice1(User user);
	void insertnotice2(User user);
	void delnotice1(User user);
	void delnotice2(User user);
	void updateUserImage(User user);
	User getreadsum(User user);
	void insertUserCity(Map<String, Object> map);
	void deleteUserCity(User user);
}
